# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 19:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='post_text',
        ),
    ]
