# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 20:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0009_slugfield_noop'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='presentation',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Presentation'),
        ),
    ]
